- name: 패키지 설치
  yum:
    name:
    - gnome-tweaks
    - gnome-extensions-app
    state: latest

- name: GNOME2 확장 설정
  ansible.builtin.command: 
    cmd: "gnome-extensions enable {{ item }}"
  with_items: "{{ extensions }}"
    

