---
# vi /etc/selinux/config
# setenforce 0
- name: /etc/selinux/config 파일 설정 - permissive
  ansible.builtin.lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: SELINUX=permissive
    
- name: setenforce 명령어 실행 - permissive
  ansible.builtin.command:
    cmd: setenforce 0

